---
- hosts: kubectrl
  become: yes
  tasks:
      - name: create sa
        command: kubectl -n kube-system create serviceaccount labkube-cluster-admin1
        register: kubectl_output
      - debug: 
          var: kubectl_output.stdout_lines
      - name: copy yml file to tmp
        ansible.builtin.copy:
          src: cluster-admin.yml
          dest: /tmp/cluster-admin.yml
      - name: test copy success
        command: ls /tmp
        register: copy_output
      - debug: 
          var: copy_output.stdout_lines
      - name: configure cluster-admin roles
        command: kubectl apply -f /tmp/cluster-admin.yml
        register: apply_output
      - debug: 
          var: apply_output.stdout_lines
      - name: set env variables
        command: kubectl -n kube-system get serviceaccount labkube-cluster-admin1 -o=jsonpath='{.secrets[0].name}'
        register: user_token_output
      - debug: 
          var: user_token_output.stdout